{% set version = "2.9.1" %}
{% set version_dash = version.replace(".", "-") %}

package:
  name: pthreads-win32
  version: {{ version }}

source:
  fn: pthreads-w32-{{ version_dash }}-release.zip
  url: ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-{{ version_dash }}-release.zip
  sha256: b9bd02958639a854461a72f72bf3e89a3c4181843b65924a54df8a50b4e5d15d
  patches:
    - timespec.patch
    - macro_redefined.patch

build:
  number: 4
  skip: True   # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

test:
  commands:
    - if not exist %LIBRARY_INC%\pthread.h exit 1
    - if not exist %LIBRARY_BIN%\pthreadVSE2.dll exit 1
    - if not exist %LIBRARY_LIB%\pthreads.lib exit 1
    - if not exist %LIBRARY_LIB%\pthread.lib exit 1
    - if not exist %LIBRARY_LIB%\pthreads_static.lib exit 1

about:
  home: https://www.sourceware.org/pthreads-win32/
  license: LGPL-2.1-or-later
  license_file: pthreads.2/COPYING.LIB
  summary: Open Source POSIX Threads for Win32

extra:
  recipe-maintainers:
    - isuruf
