travis:
  secure:
    BINSTAR_TOKEN: mDoBbGV5WchW7a0XdyvY8ZqEvYFJbo+ma2PyLZLr0rYDzhCENbmODVQNZ7+KPkPFe9F49fKSW3f0nz71gM+HivJ5UOlL26RDUJqMz06+TAOxeD/3IpSmZhRZ4fjVTCGL9w6MvtIOzLJJp/ziqexI5ASAJ/pPwcWVAJEgXnzde4u7peqLsDJCWWTpzIqVdFlmyvatBTZesClWhw3hvlwmjv+5obL8gXyBGsNlvZ+jKEiL8blUGwEHqXRcRGsMsLckiMi8UW58HCTTO12vIIhmScbmFH89a3nIsOym6swVnGCRZPWy5QeTlgMU3pDAzEKLQGVsu0XFkbef6WmO76H+eRhx79CXYBk5tnpjo2Iq1CltRogoFKDiWnqEOIuWVFdnhh9Z3BipOW7y2AyZ8pDyWT+2uJUUq7J6I6aorEcj2b9V3Axk3JdDwCfTTcun0FXutfsg8xuzbQqbihfGoeK5oXwQv0NIx0rVZbw+z8rBjKbNEOYeq/uakDQkKR2eZL+ldcMCFc2HTvRAqxLKDQ+Xk+ucCRLndOWaNzaXShD4kATa1XcefUGEmzyCKqSY2goqGpCzfj5womVncB3j1LvxXA5Tm/FlC53U2KRBPEKUbMhfqgwr6qbBMsaYVFls+RV61dO/iMpBiX4gxcBPzoAevHv5vMfRpyFF4eJEbeLdR7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
